language: perl

install:
  - cpanm --installdeps --skip-satisfied . 

script:
  - prove -l

after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls

